### ISSUE TITLE
GPS Ros driver

### ISSUE THREAD

**Issue by Cirromulus** [Cirromulus/pilsbot#10]

**Comment by PimpMyPizza** [comment]
I have the UBOX GY-GPS6MV2 [Datasheet](https://www.u-blox.com/sites/default/files/products/documents/NEO-6_DataSheet_%28GPS.G6-HW-09005%29.pdf?utm_source=en%2Fimages%2Fdownloads%2FProduct_Docs%2FNEO-6_DataSheet_%28GPS.G6-HW-09005%29.pdf), which already has [ROS drivers](http://wiki.ros.org/ublox).
